version: '3.8'

services:
  interval-timer-app:
    build: .
    image: ghcr.io/binuengoor/interval-timer-app:latest
    container_name: interval-timer-app
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    restart: always