version: '3.8'

services:
  timer-app:
    image: ghcr.io/binuengoor/timer-app:latest
    container_name: interval-timer-app
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    restart: always